spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devchecklist_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info

server:
  port: 8080